from . import backends
from . import cuda
from . import nn as nn
from . import optim as optim


class Tensor:
    def backward(
        self,
        gradient: Tensor | None = None,
        retain_graph: bool | None = None,
        create_graph: bool = False,
        inputs: tuple[Tensor, ...] | None = None,
    ) -> None: ...
    def detach(self) -> Tensor: ...
    def clone(self) -> Tensor: ...
    def float(self) -> Tensor: ...
    def mean(self, dim: int | None = None) -> Tensor: ...
    def sum(self, dim: int | None = None) -> Tensor: ...
    def scatter_(self, dim: int, index: Tensor, value: float) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def clamp(self, min: float | None = None, max: float | None = None) -> Tensor: ...
    def any(self) -> bool: ...
    def __float__(self) -> float: ...
    def __add__(self, other: object) -> Tensor: ...
    def __sub__(self, other: object) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __mul__(self, other: object) -> Tensor: ...
    def __truediv__(self, other: object) -> Tensor: ...
    def __gt__(self, other: object) -> Tensor: ...
    def __getitem__(self, index: object) -> Tensor: ...
    @property
    def shape(self) -> tuple[int, ...]: ...


class Generator:
    def __init__(self, device: object | None = None) -> None: ...
    def manual_seed(self, seed: int) -> Generator: ...


class no_grad:
    def __enter__(self) -> None: ...
    def __exit__(self, *args: object) -> None: ...


long: object
float32: dtype
float64: dtype


class dtype: ...


class version:
    cuda: str | None


def randperm(n: int, generator: Generator | None = None) -> Tensor: ...
def randint(low: int, high: int, size: tuple[int, ...] | int) -> Tensor: ...
def rand(*size: int, generator: Generator | None = None) -> Tensor: ...
def randn(*size: int) -> Tensor: ...
def ones(*size: int) -> Tensor: ...
def empty(*size: int, dtype: object | None = None) -> Tensor: ...
def tensor(data: object, dtype: object | None = None) -> Tensor: ...
def equal(first: Tensor, second: Tensor) -> bool: ...
def softmax(input: Tensor, dim: int) -> Tensor: ...
def log(input: Tensor) -> Tensor: ...
def zeros_like(input: Tensor) -> Tensor: ...
def manual_seed(seed: int) -> Generator: ...
def get_default_dtype() -> dtype: ...
def set_default_dtype(dtype: object) -> None: ...
def set_float32_matmul_precision(precision: str) -> None: ...
def get_float32_matmul_precision() -> str: ...
def use_deterministic_algorithms(mode: bool) -> None: ...
def are_deterministic_algorithms_enabled() -> bool: ...
