from typing import Any

class Expr:
    def __add__(self, other: float | int | Expr) -> Expr: ...
    def __radd__(self, other: float | int) -> Expr: ...
    def __sub__(self, other: float | int | Expr) -> Expr: ...
    def __rsub__(self, other: float | int) -> Expr: ...
    def __mul__(self, other: float | int | Expr) -> Expr: ...
    def __rmul__(self, other: float | int) -> Expr: ...
    def __le__(self, other: float | int | Expr) -> Expr: ...
    def __ge__(self, other: float | int | Expr) -> Expr: ...
    def __eq__(self, other: object) -> Expr: ...

class Var(Expr): ...
class Constraint: ...

def quicksum(terms: Any) -> Expr: ...

class Model:
    def __init__(self, name: str = "") -> None: ...
    def hideOutput(self) -> None: ...
    def freeTransform(self) -> None: ...
    def setRealParam(self, name: str, value: float) -> None: ...
    def setIntParam(self, name: str, value: int) -> None: ...
    def setBoolParam(self, name: str, value: bool) -> None: ...
    def addVar(
        self,
        name: str = "",
        vtype: str = "C",
        lb: float = 0.0,
        ub: float | None = None,
        obj: float = 0.0,
    ) -> Var: ...
    def addCons(
        self,
        cons: Expr,
        name: str = "",
        removable: bool = False,
    ) -> Constraint: ...
    def delCons(self, cons: Constraint) -> None: ...
    def setObjective(self, objective: Expr | float, sense: str = "minimize") -> None: ...
    def optimize(self) -> None: ...
    def getStatus(self) -> str: ...
    def getGap(self) -> float: ...
    def getObjVal(self) -> float: ...
    def getVal(self, expr: Expr) -> float: ...
